// Mapeo de países a banderas emoji
const countryFlags = {
  'Mexico': '🇲🇽',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  'Czech Republic': '🇨🇿',
  'Argentina': '🇦🇷',
  'Brazil': '🇧🇷',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Spain': '🇪🇸',
  'England': '🇬🇧',
  'Italy': '🇮🇹',
  'Netherlands': '🇳🇱',
  'Portugal': '🇵🇹',
  'Belgium': '🇧🇪',
  'Croatia': '🇭🇷',
  'Uruguay': '🇺🇾',
  'Canada': '🇨🇦',
  'United States': '🇺🇸',
  'Morocco': '🇲🇦',
  'Senegal': '🇸🇳',
  'Ghana': '🇬🇭',
  'Egypt': '🇪🇬',
  'Japan': '🇯🇵',
  'Australia': '🇦🇺',
  'Iran': '🇮🇷',
  'Saudi Arabia': '🇸🇦',
  'Ukraine': '🇺🇦',
  'Poland': '🇵🇱',
  'Serbia': '🇷🇸',
  'Greece': '🇬🇷',
  'Turkey': '🇹🇷',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Sweden': '🇸🇪',
  'Denmark': '🇩🇰',
  'Norway': '🇳🇴',
  'Finland': '🇫🇮',
  'Iceland': '🇮🇸',
  'Slovenia': '🇸🇮',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Bulgaria': '🇧🇬',
  'Israel': '🇮🇱',
  'Lebanon': '🇱🇧',
  'Oman': '🇴🇲',
  'UAE': '🇦🇪',
  'Qatar': '🇶🇦',
  'Uzbekistan': '🇺🇿',
  'Kyrgyzstan': '🇰🇬',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Indonesia': '🇮🇩',
  'Malaysia': '🇲🇾',
  'Singapore': '🇸🇬',
  'Philippines': '🇵🇭',
  'Hong Kong': '🇭🇰',
  'Taiwan': '🇹🇼',
  'New Zealand': '🇳🇿',
  'Fiji': '🇫🇯',
  'Papua New Guinea': '🇵🇬',
  'Solomon Islands': '🇸🇧',
  'Samoa': '🇼🇸',
  'Vanuatu': '🇻🇺',
  'Jamaica': '🇯🇲',
  'Trinidad and Tobago': '🇹🇹',
  'Costa Rica': '🇨🇷',
  'Panama': '🇵🇦',
  'Honduras': '🇭🇳',
  'El Salvador': '🇸🇻',
  'Guatemala': '🇬🇹',
  'Ecuador': '🇪🇨',
  'Peru': '🇵🇪',
  'Chile': '🇨🇱',
  'Colombia': '🇨🇴',
  'Paraguay': '🇵🇾',
  'Bolivia': '🇧🇴',
  'Venezuela': '🇻🇪',
  'Guyana': '🇬🇾',
  'Suriname': '🇸🇷',
};

function getFlag(countryName) {
  return countryFlags[countryName] || '🏳️';
}

module.exports = { countryFlags, getFlag };
